import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import type { Metadata } from 'next'
import './globals.css'
import ClientOnly from './components/ClientOnly'
import RegisterModal from './components/modals/RegisterModal'
import RentModal from './components/modals/RentModal'
import ToasterProvider from './providers/ToasterProvider'
import LoginModal from './components/modals/LoginModal'
import getCurrentUser from './actions/getCurrentUser'
import SearchModal from './components/modals/SearchModal'



export const metadata: Metadata = {
  title: 'AirBnb',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider/>
          <SearchModal/>
          <RentModal/>
          <RegisterModal/>
          <LoginModal/>
          <Navbar currentUser={currentUser}/>

        </ClientOnly>
        <div className='pb-20 pt-28'
        >{children}</div>
        
        </body>
    </html>
  )
}
